app:
  scheduler:
    enable: true
    interval: PT10s
    force-check-delay: PT10s
  clients:
    gitHub:
      url: https://api.github.com
    stackOverflow:
      url: https://api.stackexchange.com/2.3
    bot:
      url: http://localhost:8090

springdoc:
  swagger-ui:
    path=/swagger-ui

spring:
  application:
    name: scrapper

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
