app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
  clients:
    gitHub: https://api.github.com
    stackOverflow: https://api.stackexchange.com/2.3
    bot: http://localhost:8090

springdoc:
  swagger-ui:
    path=/swagger-ui

spring:
  application:
    name: scrapper

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
